name: PowerPortals
version: '${project.version}'
main: io.github.nsdigirolamo.powerportals.PowerPortals
api-version: 1.18
website: nsdigirolamo.github.io

commands:
  link:
    description: Link two PowerPortals
    permissions: powerportals.commands.link
    usage: /link <name>

permissions:

  powerportals.*:
    description: Wildcard permission for PowerPortals plugin
    default: op
    children:
      powerportals.commands.*: true

  powerportals.commands.*:
    description: Wildcard permission for commands.
    default: op
    children:
      powerportals.commands.link: true

  powerportals.commands.link:
    description: Allow use of /link
    default: true
