name: PowerPortals
version: '${project.version}'
main: io.github.nsdigirolamo.powerportals.PowerPortals
api-version: 1.18
depend: [WorldEdit]
commands:
  link:
    description: Link a PowerPortal to another PowerPortal.
    permissions: powerportals.commands.link
    usage: /link <name>
  portals:
    descritpion: List all owned PowerPortals.
    permissions: powerportals.commands.portals
    usage: /portals
permissions:
  powerportals.*:
    description: Wildcard permission for powerportals.
    default: op
    children:
      powerportals.commands.*: true
  powerportals.commands.*:
    description: Wildcard permission for commands.
    default: op
    children:
      powerportals.commands.link: true
      powerportals.commands.portals: true
  powerportals.commands.link:
    description: Allow use of /link
    default: true
  powerportals.commands.portals:
    description: Allow use of /portals
    default: true
