name: PowerPortals
version: '${project.version}'
main: io.github.nsdigirolamo.powerportals.PowerPortals
api-version: 1.18
website: nsdigirolamo.github.io

commands:
  link:
    description: Link two PowerPortals
    permissions: powerportals.commands.link
    usage: /link <name>
  portals:
    description: List owned PowerPortals
    permissions: powerportals.commands.portals
    usage: /portals <page>

permissions:

  powerportals.portals.byPassMax:
    description: Allows a player to own more than the maximum number of portals
    default: op

  powerportals.commands.link:
    description: Allow use of /link
    default: true

  powerportals.commands.portals:
    description: Allow use of /portals
    default: true
