name: PowerPortals
version: '${project.version}'
main: io.github.nsdigirolamo.powerportals.PowerPortals
api-version: 1.18
website: nsdigirolamo.github.io

commands:

  link:
    description: Link two PowerPortals.
    permissions: powerportals.commands.link
    usage: /link <portalName> [<password>]

  portals:
    description: List owned PowerPortals.
    permissions: powerportals.commands.portals
    usage: /portals [<pageNumber>|all]

  pwarp:
    description: Warp to a PowerPortal.
    permissions: powerportals.commands.pwarp
    usage: /pwarp <portalName>

  ppassword:
    description: Set or delete a PowerPortal's password.
    permissions: powerportals.commands.ppassword
    usage: /ppassword <portalName> [set|delete] [<password>]

permissions:

  powerportals.portals.bypassMax:
    description: Allows a player to own more than the maximum number of portals.
    default: op

  powerportals.portals.bypassPassword:
    description: Allows a player to travel to a portal without knowing its password.
    default: op

  powerportals.commands.link:
    description: Allow use of the /link command.
    default: true

  powerportals.commands.portals:
    description: Allow use of the /portals command.
    default: true

  powerportals.commands.portals.all:
    description: Allow use of the /portals all command.
    default: op

  powerportals.commands.pwarp:
    description: Allow use of the /pwarp command.
    default: op

  powerportals.commands.ppassword:
    description: Allow use of the /ppassword command.
    default: true
