name: PowerPortals
version: '${project.version}'
main: io.github.nsdigirolamo.powerportals.PowerPortals
api-version: 1.18
website: nsdigirolamo.github.io

commands:

  link:
    description: Link two PowerPortals.
    permissions: powerportals.commands.link
    usage: /link <portalName>

  portals:
    description: List owned PowerPortals.
    permissions: powerportals.commands.portals
    usage: /portals [<pageNumber>|all]

  pwarp:
    description: Warp to a PowerPortal.
    permissions: powerportals.commands.pwarp
    usage: /pwarp <portalName>

permissions:

  powerportals.portals.byPassMax:
    description: Allows a player to own more than the maximum number of portals.
    default: op

  powerportals.commands.link:
    description: Allow use of the /link command.
    default: true

  powerportals.commands.portals:
    description: Allow use of the /portals command.
    default: true

  powerportals.commands.portals.all:
    description: Allow use of the /portals all command.
    default: op

  powerportals.commands.pwarp:
    description: Allow use of the /pwarp command.
    default: op
