name: PowerPortals
version: '${project.version}'
main: io.github.nsdigirolamo.powerportals.PowerPortals
api-version: 1.18
commands:
  link:
    description: Link a portal to a different portal.
    permissions: powerportals.link
    usage: /link <name>
permissions:
  powerportals.*:
    description: Wildcard permission.
    default: op
    children:
      powerportals.link: true
  powerportals.link:
    description: Allow use of /link
    default: true